### ISSUE TITLE
Update python workflow for cubit 

### ISSUE THREAD

**Issue by knarfnitram** [imcs-compsim/cubitpy#45]
Currently, we recommend using a `virtual-env` for installation of all python packages required within cubit. 
Since this seems to be outdated (most of the users are using some variant of `Conda` anyway) and currently not working, since `setup.py` is missing, I suggest updating the workflow to `conda` as we are doing for `meshpy` . 

Definition of Done:
- [ ] Update Readme with Conda workflow
- [ ] Update Testing?

**Comment by isteinbrecher** [comment]
Did you check the new readme (with the latest commit to `main`)? Should already cover the first of your points. I don't get the point regarding the missing `setup.py`. We are using the same workflow for CubitPy as for MeshPy.

**Comment by knarfnitram** [comment]
ah ok, you updated it already. I think we can close this then?

**Comment by isteinbrecher** [comment]
I just updated the README. If your question was just regarding the readme, feel free to close this issue.
